const ropa = [
    {
        id:1,
        nombre: "camisas",
        price: "$5000",
        image: "./img/camisa.jpg",
    },
     {
        id:2,
        nombre: "camisas",
        price: "$6500",
        image: "./img/camisa2.jpg",
    },
    {
        id:3,
        nombre: "blusas",
        price: "$8000",
        image: "./img/blusa.png",
    },
    {
        id:4,
        nombre: "blusas",
        price: "$7000",
        image: "./img/blusa3.jpg",
    },
    {
        id:5,
        nombre: "blusas",
        price: "$9000",
        image: "./img/blusa4.jpg",
    },
    {
        id:6,
        nombre: "buzo",
        price: "$15000",
        image: "./img/buzo.jpg",
    },
    {
        id:7,
        nombre: "pantalon",
        price: "$20000",
        image: "./img/pantalon.jpg",
    },
    {
        id:1,
        nombre: "pantalon",
        price: "$30000",
        image: "./img/pantalon2.jpg",
    },
    {
        id:1,
        nombre: "pollera",
        price: "$9000",
        image: "./img/pollera.jpg",
    },
    {
        id:1,
        nombre: "pollera",
        price: "$9000",
        image: "./img/pollera2.jpg",
    },
    {
        id:1,
        nombre: "pollera",
        price: "$10000",
        image: "./img/pollera3.jpg",
    },
    {
        id:1,
        nombre: "pollera",
        price: "$10000",
        image: "./img/pollera4.jpg",
    },
    {
        id:1,
        nombre: "vestido",
        price: "$25000",
        image: "./img/vestido.jpg",
    },
    {
        id:1,
        nombre: "vestido",
        price: "$20000",
        image: "./img/vestido2.jpg",
    },
    {
        id:1,
        nombre: "vestido",
        price: "$15000",
        image: "./img/vestido3.jpg",
    },
    {
        id:1,
        nombre: "vestido",
        price: "$35000",
        image: "./img/vestido4.jpg",
    },

    {
        id:1,
        nombre: "zapatos",
        price: "$25000",
        image: "./img/zapatos.jpg",
    },
    {
        id:1,
        nombre: "zapatos",
        price: "$3000",
        image: "./img/zapatos2.jpg",
    },
    {
        id:1,
        nombre: "zapatos",
        price: "$50000",
        image: "./img/zapatos3.jpg",
    },
    {
        id:1,
        nombre: "zapatos",
        price: "$45000",
        image: "./img/zapatos4.jpg",
    },
    {
        id:1,
        nombre: "zapatos",
        price: "$50000",
        image: "./img/zapatos5.jpg",
    },
    {
        id:1,
        nombre: "zapatos",
        price: "$60000",
        image: "./img/zapatos6.jpg",
    },
    {
        id:1,
        nombre: "zapatos",
        price: "$65000",
        image: "./img/zapatos7.jpg",
    },
    {
        id:1,
        nombre: "accesorios",
        price: "$5000",
        image: "./img/accesorio2.jpg",
    },
    {
        id:1,
        nombre: "accesorios",
        price: "$6000",
        image: "./img/accesorio3.jpg",
    },
    {
        id:1,
        nombre: "accesorios",
        price: "$3000",
        image: "./img/accesorio4.jpg",
    },
    {
        id:1,
        nombre: "accesorios",
        price: "$15000",
        image: "./img/accesorio5.jpg",
    },
    {
        id:1,
        nombre: "accesorios",
        price: "$7000",
        image: "./img/accesorios.jpg",
    },
]
